<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('courses')->insert([
            [
                'crsId' => 1,
                'crsNameEn' => 'Basic Life Support',
                'crsNameAr' => 'الإنعاش القلبي الأساسي',
                'typId' => 1,
                'crsImage' => 'https://www.hlonlinetraining.co.uk/wp-content/uploads/2018/05/online%E2%80%8B-health-and-social-care-courses.jpg',
                'crsDate' => Carbon::now(),
                'spcId' => 1,
                'spcSubId' => 2,
                'crsPrice' => 250.00,
                'crsDescriptionEn' => 'Introductory course on CPR and emergency response.',
                'crsDescriptionAr' => 'دورة تمهيدية عن الإنعاش القلبي والتنفس الطارئ.',
                'crsStatus' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'crsId' => 2,
                'crsNameEn' => 'Advanced Cardiac Life Support',
                'crsNameAr' => 'الإنعاش القلبي المتقدم',
                'typId' => 1,
                'crsDate' => Carbon::now()->addDays(10),
                'spcId' => 1,
                'crsImage' => 'https://www.hlonlinetraining.co.uk/wp-content/uploads/2018/05/online%E2%80%8B-health-and-social-care-courses.jpg',
                'spcSubId' => 2,
                'crsPrice' => 500.00,
                'crsDescriptionEn' => 'Advanced training for handling cardiac arrest and emergencies.',
                'crsDescriptionAr' => 'تدريب متقدم للتعامل مع السكتة القلبية والطوارئ.',
                'crsStatus' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'crsId' => 3,
                'crsNameEn' => 'Pediatric Advanced Life Support',
                'crsNameAr' => 'الإنعاش المتقدم للأطفال',
                'typId' => 1,
                'crsDate' => Carbon::now()->addDays(20),
                'spcId' => 1,
                'spcSubId' => 2,
                'crsImage' => 'https://www.hlonlinetraining.co.uk/wp-content/uploads/2018/05/online%E2%80%8B-health-and-social-care-courses.jpg',
                'crsPrice' => 600.00,
                'crsDescriptionEn' => 'Emergency pediatric life support for healthcare professionals.',
                'crsDescriptionAr' => 'دورة حول دعم الحياة الطارئ للأطفال لمقدمي الرعاية الصحية.',
                'crsStatus' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'crsId' => 4,
                'crsNameEn' => 'Trauma Nursing Core Course',
                'crsNameAr' => 'دورة أساسيات تمريض الإصابات',
                'typId' => 2,
                'crsDate' => Carbon::now()->addDays(30),
                'spcId' => 1,
                'crsImage' => 'https://www.hlonlinetraining.co.uk/wp-content/uploads/2018/05/online%E2%80%8B-health-and-social-care-courses.jpg',
                'spcSubId' => 2,
                'crsPrice' => 450.00,
                'crsDescriptionEn' => 'Focused training on trauma assessment and interventions.',
                'crsDescriptionAr' => 'تدريب متخصص على تقييم الإصابات والتدخلات.',
                'crsStatus' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'crsId' => 5,
                'crsNameEn' => 'Emergency Medical Technician',
                'crsNameAr' => 'فني الطوارئ الطبية',
                'typId' => 2,
                'crsDate' => Carbon::now()->addDays(45),
                'spcId' => 1,
                'crsImage' => 'https://www.hlonlinetraining.co.uk/wp-content/uploads/2018/05/online%E2%80%8B-health-and-social-care-courses.jpg',
                'spcSubId' => 2,
                'crsPrice' => 1200.00,
                'crsDescriptionEn' => 'Comprehensive EMT course covering pre-hospital care.',
                'crsDescriptionAr' => 'دورة شاملة لفنيي الطوارئ الطبية تشمل الرعاية قبل المستشفى.',
                'crsStatus' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'crsId' => 6,
                'crsNameEn' => 'First Aid and Safety',
                'crsNameAr' => 'الإسعافات الأولية والسلامة',
                'typId' => 3,
                'crsDate' => Carbon::now()->addDays(15),
                'crsImage' => 'https://www.hlonlinetraining.co.uk/wp-content/uploads/2018/05/online%E2%80%8B-health-and-social-care-courses.jpg',
                'spcId' => 1,
                'spcSubId' => 2,
                'crsPrice' => 150.00,
                'crsDescriptionEn' => 'Basic first aid skills and workplace safety procedures.',
                'crsDescriptionAr' => 'مهارات الإسعافات الأولية الأساسية وإجراءات السلامة في مكان العمل.',
                'crsStatus' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'crsId' => 7,
                'crsNameEn' => 'Disaster Preparedness Training',
                'crsNameAr' => 'تدريب الاستعداد للكوارث',
                'typId' => 3,
                'crsDate' => Carbon::now()->addDays(60),
                'spcId' => 1,
                'crsImage' => 'https://www.hlonlinetraining.co.uk/wp-content/uploads/2018/05/online%E2%80%8B-health-and-social-care-courses.jpg',
                'spcSubId' => 2,
                'crsPrice' => 700.00,
                'crsDescriptionEn' => 'Emergency response and preparedness for disasters.',
                'crsDescriptionAr' => 'الاستجابة للطوارئ والاستعداد للكوارث.',
                'crsStatus' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'crsId' => 8,
                'crsNameEn' => 'Pharmacology for Nurses',
                'crsNameAr' => 'علم الأدوية للتمريض',
                'typId' => 1,
                'crsDate' => Carbon::now()->addDays(25),
                'spcId' => 1,
                'crsImage' => 'https://www.hlonlinetraining.co.uk/wp-content/uploads/2018/05/online%E2%80%8B-health-and-social-care-courses.jpg',
                'spcSubId' => 2,
                'crsPrice' => 800.00,
                'crsDescriptionEn' => 'Understanding pharmacology and medication safety.',
                'crsDescriptionAr' => 'فهم علم الأدوية وسلامة الأدوية.',
                'crsStatus' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'crsId' => 9,
                'crsNameEn' => 'Infection Control Practices',
                'crsNameAr' => 'ممارسات مكافحة العدوى',
                'crsImage' => 'https://www.hlonlinetraining.co.uk/wp-content/uploads/2018/05/online%E2%80%8B-health-and-social-care-courses.jpg',
                'typId' => 2,
                'crsDate' => Carbon::now()->addDays(40),
                'spcId' => 1,
                'spcSubId' => 2,
                'crsPrice' => 350.00,
                'crsDescriptionEn' => 'Best practices for infection prevention and control in healthcare.',
                'crsDescriptionAr' => 'أفضل الممارسات لمنع العدوى والسيطرة عليها في الرعاية الصحية.',
                'crsStatus' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'crsId' => 10,
                'crsNameEn' => 'Neonatal Resuscitation Program',
                'crsNameAr' => 'برنامج إنعاش حديثي الولادة',
                'typId' => 1,
                'crsDate' => Carbon::now()->addDays(50),
                'spcId' => 1,
                'spcSubId' => 2,
                'crsImage' => 'https://www.hlonlinetraining.co.uk/wp-content/uploads/2018/05/online%E2%80%8B-health-and-social-care-courses.jpg',
                'crsPrice' => 900.00,
                'crsDescriptionEn' => 'Resuscitation techniques for newborn infants.',
                'crsDescriptionAr' => 'تقنيات الإنعاش لحديثي الولادة.',
                'crsStatus' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'crsId' => 11,
                'crsNameEn' => 'Critical Care Nursing',
                'crsNameAr' => 'تمريض العناية المركزة',
                'typId' => 3,
                'crsDate' => Carbon::now()->addDays(70),
                'crsImage' => 'https://www.hlonlinetraining.co.uk/wp-content/uploads/2018/05/online%E2%80%8B-health-and-social-care-courses.jpg',
                'spcId' => 1,
                'spcSubId' => 2,
                'crsPrice' => 1100.00,
                'crsDescriptionEn' => 'Specialized training for ICU nurses and critical patients.',
                'crsDescriptionAr' => 'تدريب متخصص للممرضين في وحدات العناية المركزة والمرضى الحرجين.',
                'crsStatus' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
        ]);
    }
}
